version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile  # Or "Dockerfile" if renamed
    container_name: switchmap-api
    user: "${API_UID}:${API_GID}"
    volumes:
      - .:/home/switchmap/api
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/switchmap
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - switchmap-network

  db:
    image: postgres:14
    container_name: switchmap-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: switchmap
    ports:
      - "5432:5432"
    networks:
      - switchmap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  switchmap-network:
    driver: bridge
